# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170302_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='polls',
            field=models.IntegerField(default=0),
        ),
    ]
