# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-18 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_photo_polls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='color1',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='polls',
            new_name='first',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='color2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='question1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='question2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='question3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='question4',
            field=models.IntegerField(default=0),
        ),
    ]
